version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: top-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - micro-app-network
    restart:
      unless-stopped

  nats:
    image: 'nats:2.8.3-alpine'
    container_name: top-nats
    ports:
      - "4222:4222"
    networks:
      - micro-app-network
    restart:
      unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: top-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    networks:
      - micro-app-network
    restart:
      unless-stopped
    depends_on:
      - redis
      - jwt-service

networks:
  micro-app-network:
    name: micro-app-network
    attachable: true
    driver: overlay