export enum ActionTypes {
  REGISTER = '[AUTH] REGISTER',
  REGISTER_SUCCESS = '[AUTH] REGISTER SUCCESS',
  REGISTER_FAILURE = '[AUTH] REGISTER FAILURE',

  AUTH = '[AUTH] LOGIN',
  AUTH_SUCCESS = '[AUTH] LOGIN SUCCESS',
  AUTH_FAILURE = '[AUTH] LOGIN FAILURE',
}
